"""message

Revision ID: 17316dd497ff
Revises: 7824b02696dd
Create Date: 2024-07-02 21:52:53.220817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17316dd497ff'
down_revision = '7824b02696dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
