"""message

Revision ID: 5e96ee9b5e10
Revises: 0105d9ee525b
Create Date: 2024-07-08 08:14:28.873343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e96ee9b5e10'
down_revision = '0105d9ee525b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
